### PR TITLE
Read me

### PR DESCRIPTION
**Pull request by BDVGitHub**

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Duplicate of #37

**Comment by BDVGitHub** [comment]
@Jean-BaptisteC some uses readthedocs for explenation or documentation. Maybe to set one one up for Panoromax app also?

https://about.readthedocs.com/?ref=readthedocs.org

**Comment by Jean-BaptisteC** [comment]
IMO, it's too complex for the size of the project.
And I'm not sure developers of project want to open access to repository to readthedoc website.

**Comment by BDVGitHub** [comment]
@Jean-BaptisteC ok understand. My I ask, do you use [GitHub CLI](https://cli.github.com/) or [GitHub desktop](https://github.com/apps/desktop) or something else? Can you send a link to the correct dart and docker? Thx

**Comment by Jean-BaptisteC** [comment]
I use Github desktop, but you can use any software to push your changes or just send changes directly on github website.
To install dart, I guess you can follow instructions present on flutter website

**Pull request closed without merging**
