### PR TITLE
Prepare repository for fdroid publication

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
This PR creates structure directories to publish on Fdroid following this [documentation](https://f-droid.org/fr/docs/All_About_Descriptions_Graphics_and_Screenshots/)

- I have added directories for en and fr language
- Added short and full description in en and fr (short description is limited to 80 characters)
- Added app icon

### CODE REVIEW

**Comment by Jean-BaptisteC** [comment]
Cc @OtterWays

**Comment by natrius** [comment]
Is this some kind of rendering-issue or might there be a mistake? It seems there is an additional `.txt` in the filenames. `metadata/en-US/full_description.txt.txt` and not as i would expect `metadata/en-US/full_description.txt`

**Comment by Jean-BaptisteC** [comment]
Nice catch, I will fix that

**Comment by Jean-BaptisteC** [comment]
Yes directory structure is ready
Next step, publish on FDroid?

**Comment by antoine-de** [comment]
maybe we can merge this as is, and do the publication on a next step?

**Comment by Jean-BaptisteC** [comment]
Yes

**Review by antoine-de — APPROVED** [review]

**Comment by Jean-BaptisteC** [comment]
@luifr10 can be also merge 🙂

**Review by luifr10 — APPROVED** [review]

**Pull request merged**
