### PR TITLE
Update AppID

### LINKED ISSUE #24: Find a better AppID
Today, you use this AppID:
https://github.com/nobelization/panoramax-mobile-app/blob/02df2069b691827f4de3d058fa9090887eb99642/android/app/build.gradle#L45

Some suggestions:
- `com.geovisio.panoramax_mobile`
- `com.panoramax_mobile`
- `panoramax_mobile.app`

Todo:
- [x] Update app_id in gradle scripts
- [x] Update package name in [Kotlin class](https://github.com/nobelization/panoramax-mobile-app/blob/02df2069b691827f4de3d058fa9090887eb99642/android/app/src/main/kotlin/com/example/panoramax_mobile/MainActivity.kt#L1)
- [x] Update the structure of Android directories
- [x] Updata app_id in integration tests

This change needs to be done before the first release because it's not possible to update the app. If app_id is different, the app is not updated, and a new app is installed.

### PR DESCRIPTION
**Pull request by Jean-BaptisteC**
Fixes #24

I have updated appID for all platforms, updated the date of copyright, updated Android test.

### CODE REVIEW

**Comment by luifr10** [comment]
Please can you rename your commit to follow the conventional commit : https://www.conventionalcommits.org/en/v1.0.0/

**Comment by Jean-BaptisteC** [comment]
Done
I add this guideline in PR about readme :)

**Review by luifr10 — APPROVED** [review]

**Review by luifr10 — CHANGES_REQUESTED** [review]
Please rename your commit for :
- specify issue in message
- commit message start  with lower case

So for this issue : `fix: add new AppID, #24`

**Comment by Jean-BaptisteC** [comment]
Done

**Review by luifr10 — APPROVED** [review]

**Pull request merged**
