### PR TITLE
28 shooting screen

### PR DESCRIPTION
**Pull request by OtterWays**
I modified the UI according to the mockups provided.

It is now impossible to take photos in portrait mode and the buttons have been redone for landscape mode.

The burst mode is not yet implemented and will be in #33

### CODE REVIEW

**Review by Jean-BaptisteC — APPROVED** [review]
✅ Pixel 6 - Android 14

**Review by luifr10 — CHANGES_REQUESTED** [review]
Changes ok for me, can you please correct the E2E tests performed during the CI ?

**Comment by OtterWays** [comment]
> Changes ok for me, can you please correct the E2E tests performed during the CI ?

I have added a tooltip to the photo capture button. However, it is not an actual button but a GestureDetector. Consequently, the test 'iShouldSeeAButtonNamed($, 'Take a picture');' does not work. I don't want to delete this test, but I'm unsure how to modify it to make it pass.

**Comment by OtterWays** [comment]
@luifr10 I I am unable to fix the integration test.

**Comment by luifr10** [comment]
Hello @OtterWays !

integration_tests are now OK, here are the changes I've made :
- Add a scenario that checks the presence of the message when in portrait mode.
- Change last scenario that checks landscape mode
- Migrate router from go_router to get_it (easier for testing)
- Wrap capture button with IconButton to have semantic role button (for accessibility we have to be careful on this point)

I also made a rebase on the main branch, it's better to do a rebase instead of a merge to update with the main branch

**Review by silex-aline — APPROVED** [review]

**Pull request merged**
